version: '2'
services:
  drinkedidrink-app:
    image: drinkedidrink
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mariadb://drinkedidrink-mariadb:3306/drinkedidrink
      - JHIPSTER_SLEEP=120 # gives time for mariadb server to start
    ports:
      - 8123:8123
  drinkedidrink-mariadb:
    extends:
      file: mariadb.yml
      service: drinkedidrink-mariadb
